name: CryptoPRO tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  buildAndTest:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ lts/* ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean install, build, test
        run: |
          npm ci
          npm run build --if-present --openssl-legacy-provider
          npm test

  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Clean install, lint
        run: |
          npm ci
          npm run lint
